### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by teshomem** [nextgenusfs/funannotate#32]
Hi,

Tried to run it in Python 2.7.11

--------------------------------------------------------------------------------------------
[08:33:58 AM]: Running funannotate v.0.3.11
[08:33:58 AM]: No NCBI SBT file given, will use default, however if you plan to submit to NCBI, create one and pass it here '--sbt'
Traceback (most recent call last):
  File "/mnt/various/local/genome/packages/funannotate/v0.1.5/bin/funannotate-functional.py", line 221, in <module>
    Scaffolds, Proteins, Transcripts, GFF = [os.path.abspath(i) for i in [Scaffolds, Proteins, Transcripts, GFF]] #suggestion via GitHub
  File "/local/genome/packages/anaconda/2.4.1/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/local/genome/packages/anaconda/2.4.1/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

Thanks

**Comment by nextgenusfs** [comment]
Ok, what was your command for this output?  Seems like one of these file types is empty or None, hence the error.  This "fix" was based on a user suggestion, I did test it, but I can revert to original if there is a problem.  Should work fine on Python 2.7.11. Can you confirm that the proper intermediate files have been created, they would be in your `outputname/annotate_misc` folder and have these filenames: `genome.scaffolds.fa`, `genome.transcripts.fa`, `genome.proteins.fa`.  The location of the GFF file is dependent upon what you gave the script as input, so I need to know your command.  But likely it would be a file in this folder: `outputname/predict_results/species_name.gff3`.

**Comment by nextgenusfs** [comment]
Don't know if this is still a problem?  `Transcripts` was removed from this command as it can be an empty variable depending on the input.  Reopen if this is still a problem.
