### ISSUE TITLE
Problem with Funannotate_db installation

### ISSUE THREAD

**Issue by AlWa1** [nextgenusfs/funannotate#607]
When trying to install the fun annotate_db, following issue comes up - any clue what is going on?

Thanks a lot in advance! 

(funannotate) aw932@hpc:~$ funannotate setup -d $HOME/funannotate_db
-------------------------------------------------------
[Jun 16 02:36 PM]: OS: Ubuntu 20.04, 1 cores, ~ 8 GB RAM. Python: 3.9.5
[Jun 16 02:36 PM]: Running 1.8.7
[Jun 16 02:36 PM]: Database location: /home/aw932/funannotate_db
[Jun 16 02:36 PM]: Retrieving download links from GitHub Repo
[Jun 16 02:36 PM]: Parsing Augustus pre-trained species and porting to funannotate
Traceback (most recent call last):
  File "/home/aw932/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/aw932/miniconda3/envs/funannotate/lib/python3.9/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/home/aw932/miniconda3/envs/funannotate/lib/python3.9/site-packages/funannotate/setupDB.py", line 694, in main
    meropsDB(DatabaseInfo, args.force, args=args)
  File "/home/aw932/miniconda3/envs/funannotate/lib/python3.9/site-packages/funannotate/setupDB.py", line 139, in meropsDB
    type, name, version, date, records, checksum = info.get('merops')
TypeError: cannot unpack non-iterable NoneType object
(funannotate) aw932@hpc:~$ funannotate setup -d $HOME/funannotate_db
-------------------------------------------------------
[Jun 16 02:41 PM]: OS: Ubuntu 20.04, 1 cores, ~ 8 GB RAM. Python: 3.9.5
[Jun 16 02:41 PM]: Running 1.8.7
[Jun 16 02:41 PM]: Database location: /home/aw932/funannotate_db
[Jun 16 02:41 PM]: Retrieving download links from GitHub Repo
[Jun 16 02:41 PM]: Parsing Augustus pre-trained species and porting to funannotate
[Jun 16 02:41 PM]: Downloading Merops database
[Jun 16 02:41 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/merops_scan.lib Bytes: 1957603
[Jun 16 02:41 PM]: Building diamond database
[Jun 16 02:41 PM]: MEROPS Database: version=12.0 date=2017-10-04 records=5,009
[Jun 16 02:41 PM]: Downloading UniProtKB/SwissProt database
[Jun 16 02:41 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz Bytes: 89966396
[Jun 16 02:41 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/reldate.txt Bytes: 151
[Jun 16 02:41 PM]: Building diamond database
[Jun 16 02:41 PM]: UniProtKB Database: version=2021_02 date=2021-04-07 records=564,638
[Jun 16 02:41 PM]: Downloading dbCAN database
[Jun 16 02:41 PM]: Downloading: http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-HMMdb-V8.txt Bytes: 94320446
[Jun 16 02:41 PM]: Downloading: http://bcb.unl.edu/dbCAN2/download/Databases/CAZyDB.07312019.fam-activities.txt Bytes: 63489
[Jun 16 02:41 PM]: Downloading: http://bcb.unl.edu/dbCAN2/download/Databases/dbCAN-old@UGA/readme.txt Bytes: 7507
[Jun 16 02:41 PM]: Creating dbCAN HMM database
[Jun 16 02:41 PM]: dbCAN Database: version=9.0 date=2020-08-04 records=641
[Jun 16 02:41 PM]: Downloading Pfam database
[Jun 16 02:41 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz Bytes: 286543529
[Jun 16 02:41 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.clans.tsv.gz Bytes: 348181
[Jun 16 02:41 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam.version.gz Bytes: 115
[Jun 16 02:42 PM]: Creating Pfam HMM database
[Jun 16 02:42 PM]: Pfam Database: version=34.0 date=2021-03 records=19,179
[Jun 16 02:42 PM]: Downloading Repeat database
[Jun 16 02:42 PM]: Downloading: https://osf.io/vp87c/download?version=1 Bytes: 6325661
[Jun 16 02:42 PM]: Building diamond database
[Jun 16 02:42 PM]: Repeat Database: version=1.0 date=2021-06-16 records=11,950
[Jun 16 02:42 PM]: Downloading GO Ontology database
[Jun 16 02:42 PM]: Downloading: http://purl.obolibrary.org/obo/go.obo Bytes: 33828215
[Jun 16 02:42 PM]: GO ontology version=2021-05-01 date=2021-05-01 records=47,199
[Jun 16 02:42 PM]: Downloading MiBIG Secondary Metabolism database
[Jun 16 02:42 PM]: Downloading: https://dl.secondarymetabolites.org/mibig/mibig_prot_seqs_1.4.fasta Bytes: 21244378
[Jun 16 02:42 PM]: Building diamond database
[Jun 16 02:42 PM]: MiBIG Database: version=1.4 date=2021-06-16 records=31,023
[Jun 16 02:42 PM]: Downloading InterProScan Mapping file
[Jun 16 02:42 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/interpro/interpro.xml.gz Bytes: 31026896
[Jun 16 02:43 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/interpro/entry.list Bytes: 2085328
Traceback (most recent call last):
  File "/home/aw932/miniconda3/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/home/aw932/miniconda3/envs/funannotate/lib/python3.9/site-packages/funannotate/funannotate.py", line 705, in main
    mod.main(arguments)
  File "/home/aw932/miniconda3/envs/funannotate/lib/python3.9/site-packages/funannotate/setupDB.py", line 704, in main
    interproDB(DatabaseInfo, args.force, args=args)
  File "/home/aw932/miniconda3/envs/funannotate/lib/python3.9/site-packages/funannotate/setupDB.py", line 436, in interproDB
    for x in elem.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

**Comment by nextgenusfs** [comment]
I don't think the code works with python 3.9, use 3.7 or 3.8.
